title: PIMGento
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
#<url: "https://pimgento.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - page-baseurl-generator

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

versions:
   -
      name: "1"
      url: /docs/v1.0/
   -
      name: "2"
      url: /docs/v2.0/

doc_url: /docs/

defaults:
  -
    values:
      version: "v2.0"

exclude: ['scss', 'bin', 'node_modules', 'vendor', '.git', '.idea', ]

media_url: "/common/img"

github_pimgento: "https://github.com/Agence-DnD/PIMGento"
github_pimgento_2: "https://github.com/Agence-DnD/PIMGento-2"